path:
  raw: "data/raw"
  export: "data/export"

sounds:
  voice:
    name: "voice"
    format: "mp3"
    volume: 10

  ambiance:
    name: "ambiance"
    format: "mp3"
    volume: -20

  walking:
    name: "monster-footsteps-on-gravel"
    format: "mp3"
    volume: -5
    fade_in: 0
